version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=wer08
      - POSTGRES_PASSWORD=M0rg0th&CO
  web:
    build: ./backend
    volumes:
      - ./backend:/code/
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_ROOT_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports: 
      - "5173:5173"
    volumes:
      - ./frontend:/frontend

